// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyblockAuctionTracker.Models;

namespace SkyblockAuctionTracker.Migrations
{
    [DbContext(typeof(AMCDbContext))]
    partial class AMCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SkyblockAuctionTracker.Models.BazaarProductEntry", b =>
                {
                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("MappingID")
                        .HasColumnType("int");

                    b.Property<double>("BuyPrice")
                        .HasColumnType("double");

                    b.Property<double>("SellPrice")
                        .HasColumnType("double");

                    b.HasKey("Timestamp", "MappingID");

                    b.ToTable("BazaarProductEntries");
                });

            modelBuilder.Entity("SkyblockAuctionTracker.Models.BazaarProductIDMapping", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("ID", "Name");

                    b.ToTable("BazaarProductIDMappings");

                    b.HasData(
                        new
                        {
                            ID = 0,
                            Name = "INK_SACK:3"
                        },
                        new
                        {
                            ID = 1,
                            Name = "BROWN_MUSHROOM"
                        },
                        new
                        {
                            ID = 2,
                            Name = "INK_SACK:4"
                        },
                        new
                        {
                            ID = 3,
                            Name = "SPOOKY_SHARD"
                        },
                        new
                        {
                            ID = 4,
                            Name = "TARANTULA_WEB"
                        },
                        new
                        {
                            ID = 5,
                            Name = "CARROT_ITEM"
                        },
                        new
                        {
                            ID = 6,
                            Name = "ENCHANTED_POTATO"
                        },
                        new
                        {
                            ID = 7,
                            Name = "EXP_BOTTLE"
                        },
                        new
                        {
                            ID = 8,
                            Name = "ENCHANTED_SLIME_BALL"
                        },
                        new
                        {
                            ID = 9,
                            Name = "JERRY_BOX_GREEN"
                        },
                        new
                        {
                            ID = 10,
                            Name = "ENCHANTED_RED_MUSHROOM"
                        },
                        new
                        {
                            ID = 11,
                            Name = "ENCHANTED_GOLDEN_CARROT"
                        },
                        new
                        {
                            ID = 12,
                            Name = "ENCHANTED_RABBIT_HIDE"
                        },
                        new
                        {
                            ID = 13,
                            Name = "ENCHANTED_BIRCH_LOG"
                        },
                        new
                        {
                            ID = 14,
                            Name = "ENCHANTED_GUNPOWDER"
                        },
                        new
                        {
                            ID = 15,
                            Name = "ENCHANTED_MELON"
                        },
                        new
                        {
                            ID = 16,
                            Name = "ENCHANTED_SUGAR"
                        },
                        new
                        {
                            ID = 17,
                            Name = "CACTUS"
                        },
                        new
                        {
                            ID = 18,
                            Name = "ENCHANTED_BLAZE_ROD"
                        },
                        new
                        {
                            ID = 19,
                            Name = "ENCHANTED_CAKE"
                        },
                        new
                        {
                            ID = 20,
                            Name = "PUMPKIN"
                        },
                        new
                        {
                            ID = 21,
                            Name = "ENCHANTED_BROWN_MUSHROOM"
                        },
                        new
                        {
                            ID = 22,
                            Name = "WHEAT"
                        },
                        new
                        {
                            ID = 23,
                            Name = "NURSE_SHARK_TOOTH"
                        },
                        new
                        {
                            ID = 24,
                            Name = "ENCHANTED_RAW_SALMON"
                        },
                        new
                        {
                            ID = 25,
                            Name = "ENCHANTED_GLISTERING_MELON"
                        },
                        new
                        {
                            ID = 26,
                            Name = "PRISMARINE_SHARD"
                        },
                        new
                        {
                            ID = 27,
                            Name = "ENCHANTED_EMERALD"
                        },
                        new
                        {
                            ID = 28,
                            Name = "PROTECTOR_FRAGMENT"
                        },
                        new
                        {
                            ID = 29,
                            Name = "ENCHANTED_SPIDER_EYE"
                        },
                        new
                        {
                            ID = 30,
                            Name = "RED_MUSHROOM"
                        },
                        new
                        {
                            ID = 31,
                            Name = "GRAND_EXP_BOTTLE"
                        },
                        new
                        {
                            ID = 32,
                            Name = "ENCHANTED_MELON_BLOCK"
                        },
                        new
                        {
                            ID = 33,
                            Name = "MUTTON"
                        },
                        new
                        {
                            ID = 34,
                            Name = "DIAMOND"
                        },
                        new
                        {
                            ID = 35,
                            Name = "WISE_FRAGMENT"
                        },
                        new
                        {
                            ID = 36,
                            Name = "SHARK_FIN"
                        },
                        new
                        {
                            ID = 37,
                            Name = "COBBLESTONE"
                        },
                        new
                        {
                            ID = 38,
                            Name = "REFINED_MITHRIL"
                        },
                        new
                        {
                            ID = 39,
                            Name = "RAW_FISH"
                        },
                        new
                        {
                            ID = 40,
                            Name = "SPIDER_EYE"
                        },
                        new
                        {
                            ID = 41,
                            Name = "ENCHANTED_PUFFERFISH"
                        },
                        new
                        {
                            ID = 42,
                            Name = "POTATO_ITEM"
                        },
                        new
                        {
                            ID = 43,
                            Name = "ENCHANTED_HUGE_MUSHROOM_1"
                        },
                        new
                        {
                            ID = 44,
                            Name = "REFINED_DIAMOND"
                        },
                        new
                        {
                            ID = 45,
                            Name = "ENCHANTED_COBBLESTONE"
                        },
                        new
                        {
                            ID = 46,
                            Name = "TIGHTLY_TIED_HAY_BALE"
                        },
                        new
                        {
                            ID = 47,
                            Name = "ENCHANTED_HUGE_MUSHROOM_2"
                        },
                        new
                        {
                            ID = 48,
                            Name = "PORK"
                        },
                        new
                        {
                            ID = 49,
                            Name = "PRISMARINE_CRYSTALS"
                        },
                        new
                        {
                            ID = 50,
                            Name = "ICE"
                        },
                        new
                        {
                            ID = 51,
                            Name = "TIGER_SHARK_TOOTH"
                        },
                        new
                        {
                            ID = 52,
                            Name = "HUGE_MUSHROOM_1"
                        },
                        new
                        {
                            ID = 53,
                            Name = "ICE_BAIT"
                        },
                        new
                        {
                            ID = 54,
                            Name = "HUGE_MUSHROOM_2"
                        },
                        new
                        {
                            ID = 55,
                            Name = "LOG_2:1"
                        },
                        new
                        {
                            ID = 56,
                            Name = "ENCHANTED_SNOW_BLOCK"
                        },
                        new
                        {
                            ID = 57,
                            Name = "STRING"
                        },
                        new
                        {
                            ID = 58,
                            Name = "GOLDEN_TOOTH"
                        },
                        new
                        {
                            ID = 59,
                            Name = "HYPER_CATALYST"
                        },
                        new
                        {
                            ID = 60,
                            Name = "RABBIT_FOOT"
                        },
                        new
                        {
                            ID = 61,
                            Name = "REDSTONE"
                        },
                        new
                        {
                            ID = 62,
                            Name = "JERRY_BOX_GOLDEN"
                        },
                        new
                        {
                            ID = 63,
                            Name = "PUMPKIN_GUTS"
                        },
                        new
                        {
                            ID = 64,
                            Name = "ENCHANTED_CACTUS_GREEN"
                        },
                        new
                        {
                            ID = 65,
                            Name = "BOOSTER_COOKIE"
                        },
                        new
                        {
                            ID = 66,
                            Name = "ENCHANTED_CARROT_ON_A_STICK"
                        },
                        new
                        {
                            ID = 67,
                            Name = "ENCHANTED_COOKIE"
                        },
                        new
                        {
                            ID = 68,
                            Name = "ENCHANTED_LAPIS_LAZULI_BLOCK"
                        },
                        new
                        {
                            ID = 69,
                            Name = "ENCHANTED_ENDSTONE"
                        },
                        new
                        {
                            ID = 70,
                            Name = "COLOSSAL_EXP_BOTTLE"
                        },
                        new
                        {
                            ID = 71,
                            Name = "ENCHANTED_SAND"
                        },
                        new
                        {
                            ID = 72,
                            Name = "ENCHANTED_STRING"
                        },
                        new
                        {
                            ID = 73,
                            Name = "STRONG_FRAGMENT"
                        },
                        new
                        {
                            ID = 74,
                            Name = "SLIME_BALL"
                        },
                        new
                        {
                            ID = 75,
                            Name = "ENCHANTED_ACACIA_LOG"
                        },
                        new
                        {
                            ID = 76,
                            Name = "HOLY_FRAGMENT"
                        },
                        new
                        {
                            ID = 77,
                            Name = "SNOW_BALL"
                        },
                        new
                        {
                            ID = 78,
                            Name = "ENCHANTED_EGG"
                        },
                        new
                        {
                            ID = 79,
                            Name = "SAND"
                        },
                        new
                        {
                            ID = 80,
                            Name = "SOUL_FRAGMENT"
                        },
                        new
                        {
                            ID = 81,
                            Name = "RAW_CHICKEN"
                        },
                        new
                        {
                            ID = 82,
                            Name = "ANCIENT_CLAW"
                        },
                        new
                        {
                            ID = 83,
                            Name = "ENCHANTED_GHAST_TEAR"
                        },
                        new
                        {
                            ID = 84,
                            Name = "ENCHANTED_LAPIS_LAZULI"
                        },
                        new
                        {
                            ID = 85,
                            Name = "ENCHANTED_COCOA"
                        },
                        new
                        {
                            ID = 86,
                            Name = "CARROT_BAIT"
                        },
                        new
                        {
                            ID = 87,
                            Name = "SEEDS"
                        },
                        new
                        {
                            ID = 88,
                            Name = "ENCHANTED_LEATHER"
                        },
                        new
                        {
                            ID = 89,
                            Name = "ENCHANTED_SPONGE"
                        },
                        new
                        {
                            ID = 90,
                            Name = "ENCHANTED_SHARK_FIN"
                        },
                        new
                        {
                            ID = 91,
                            Name = "HAY_BLOCK"
                        },
                        new
                        {
                            ID = 92,
                            Name = "FLINT"
                        },
                        new
                        {
                            ID = 93,
                            Name = "INK_SACK"
                        },
                        new
                        {
                            ID = 94,
                            Name = "ENCHANTED_ROTTEN_FLESH"
                        },
                        new
                        {
                            ID = 95,
                            Name = "ENCHANTED_SPRUCE_LOG"
                        },
                        new
                        {
                            ID = 96,
                            Name = "WOLF_TOOTH"
                        },
                        new
                        {
                            ID = 97,
                            Name = "ENCHANTED_GRILLED_PORK"
                        },
                        new
                        {
                            ID = 98,
                            Name = "ENCHANTED_NETHER_STALK"
                        },
                        new
                        {
                            ID = 99,
                            Name = "ENCHANTED_REDSTONE_BLOCK"
                        },
                        new
                        {
                            ID = 100,
                            Name = "ENCHANTED_QUARTZ_BLOCK"
                        },
                        new
                        {
                            ID = 101,
                            Name = "ENCHANTED_ANCIENT_CLAW"
                        },
                        new
                        {
                            ID = 102,
                            Name = "GREEN_CANDY"
                        },
                        new
                        {
                            ID = 103,
                            Name = "ENCHANTED_REDSTONE"
                        },
                        new
                        {
                            ID = 104,
                            Name = "ENCHANTED_REDSTONE_LAMP"
                        },
                        new
                        {
                            ID = 105,
                            Name = "GREAT_WHITE_SHARK_TOOTH"
                        },
                        new
                        {
                            ID = 106,
                            Name = "GRAVEL"
                        },
                        new
                        {
                            ID = 107,
                            Name = "MELON"
                        },
                        new
                        {
                            ID = 108,
                            Name = "ENCHANTED_PACKED_ICE"
                        },
                        new
                        {
                            ID = 109,
                            Name = "ENCHANTED_LAVA_BUCKET"
                        },
                        new
                        {
                            ID = 110,
                            Name = "RAW_FISH:3"
                        },
                        new
                        {
                            ID = 111,
                            Name = "ENCHANTED_PRISMARINE_SHARD"
                        },
                        new
                        {
                            ID = 112,
                            Name = "ENCHANTED_IRON_BLOCK"
                        },
                        new
                        {
                            ID = 113,
                            Name = "RECOMBOBULATOR_3000"
                        },
                        new
                        {
                            ID = 114,
                            Name = "ENCHANTED_CARROT_STICK"
                        },
                        new
                        {
                            ID = 115,
                            Name = "BONE"
                        },
                        new
                        {
                            ID = 116,
                            Name = "RAW_FISH:2"
                        },
                        new
                        {
                            ID = 117,
                            Name = "RAW_FISH:1"
                        },
                        new
                        {
                            ID = 118,
                            Name = "REVENANT_FLESH"
                        },
                        new
                        {
                            ID = 119,
                            Name = "ENCHANTED_PORK"
                        },
                        new
                        {
                            ID = 120,
                            Name = "ENCHANTED_GLOWSTONE"
                        },
                        new
                        {
                            ID = 121,
                            Name = "FEATHER"
                        },
                        new
                        {
                            ID = 122,
                            Name = "NETHERRACK"
                        },
                        new
                        {
                            ID = 123,
                            Name = "WHALE_BAIT"
                        },
                        new
                        {
                            ID = 124,
                            Name = "SPONGE"
                        },
                        new
                        {
                            ID = 125,
                            Name = "BLAZE_ROD"
                        },
                        new
                        {
                            ID = 126,
                            Name = "ENCHANTED_DARK_OAK_LOG"
                        },
                        new
                        {
                            ID = 127,
                            Name = "YOUNG_FRAGMENT"
                        },
                        new
                        {
                            ID = 128,
                            Name = "ENCHANTED_CLOWNFISH"
                        },
                        new
                        {
                            ID = 129,
                            Name = "REFINED_MINERAL"
                        },
                        new
                        {
                            ID = 130,
                            Name = "ENCHANTED_GOLD"
                        },
                        new
                        {
                            ID = 131,
                            Name = "ENCHANTED_RAW_CHICKEN"
                        },
                        new
                        {
                            ID = 132,
                            Name = "ENCHANTED_WATER_LILY"
                        },
                        new
                        {
                            ID = 133,
                            Name = "LOG:1"
                        },
                        new
                        {
                            ID = 134,
                            Name = "TITANIUM_ORE"
                        },
                        new
                        {
                            ID = 135,
                            Name = "BLUE_SHARK_TOOTH"
                        },
                        new
                        {
                            ID = 136,
                            Name = "CATALYST"
                        },
                        new
                        {
                            ID = 137,
                            Name = "LOG:3"
                        },
                        new
                        {
                            ID = 138,
                            Name = "LOG:2"
                        },
                        new
                        {
                            ID = 139,
                            Name = "BLESSED_BAIT"
                        },
                        new
                        {
                            ID = 140,
                            Name = "ENCHANTED_GLOWSTONE_DUST"
                        },
                        new
                        {
                            ID = 141,
                            Name = "ENCHANTED_INK_SACK"
                        },
                        new
                        {
                            ID = 142,
                            Name = "ENCHANTED_CACTUS"
                        },
                        new
                        {
                            ID = 143,
                            Name = "ENCHANTED_SUGAR_CANE"
                        },
                        new
                        {
                            ID = 144,
                            Name = "ENCHANTED_COOKED_SALMON"
                        },
                        new
                        {
                            ID = 145,
                            Name = "ENCHANTED_SEEDS"
                        },
                        new
                        {
                            ID = 146,
                            Name = "LOG"
                        },
                        new
                        {
                            ID = 147,
                            Name = "JACOBS_TICKET"
                        },
                        new
                        {
                            ID = 148,
                            Name = "ENCHANTED_BONE_BLOCK"
                        },
                        new
                        {
                            ID = 149,
                            Name = "GHAST_TEAR"
                        },
                        new
                        {
                            ID = 150,
                            Name = "ENCHANTED_ENDER_PEARL"
                        },
                        new
                        {
                            ID = 151,
                            Name = "UNSTABLE_FRAGMENT"
                        },
                        new
                        {
                            ID = 152,
                            Name = "PURPLE_CANDY"
                        },
                        new
                        {
                            ID = 153,
                            Name = "ENCHANTED_FERMENTED_SPIDER_EYE"
                        },
                        new
                        {
                            ID = 154,
                            Name = "SPIKED_BAIT"
                        },
                        new
                        {
                            ID = 155,
                            Name = "POLISHED_PUMPKIN"
                        },
                        new
                        {
                            ID = 156,
                            Name = "ENCHANTED_GOLD_BLOCK"
                        },
                        new
                        {
                            ID = 157,
                            Name = "ENCHANTED_JUNGLE_LOG"
                        },
                        new
                        {
                            ID = 158,
                            Name = "ENCHANTED_FLINT"
                        },
                        new
                        {
                            ID = 159,
                            Name = "IRON_INGOT"
                        },
                        new
                        {
                            ID = 160,
                            Name = "ENCHANTED_EMERALD_BLOCK"
                        },
                        new
                        {
                            ID = 161,
                            Name = "ENCHANTED_CLAY_BALL"
                        },
                        new
                        {
                            ID = 162,
                            Name = "GLOWSTONE_DUST"
                        },
                        new
                        {
                            ID = 163,
                            Name = "GOLD_INGOT"
                        },
                        new
                        {
                            ID = 164,
                            Name = "REVENANT_VISCERA"
                        },
                        new
                        {
                            ID = 165,
                            Name = "TARANTULA_SILK"
                        },
                        new
                        {
                            ID = 166,
                            Name = "TITANIC_EXP_BOTTLE"
                        },
                        new
                        {
                            ID = 167,
                            Name = "ENCHANTED_MUTTON"
                        },
                        new
                        {
                            ID = 168,
                            Name = "ENCHANTED_IRON"
                        },
                        new
                        {
                            ID = 169,
                            Name = "SUPER_COMPACTOR_3000"
                        },
                        new
                        {
                            ID = 170,
                            Name = "SUPER_EGG"
                        },
                        new
                        {
                            ID = 171,
                            Name = "STOCK_OF_STONKS"
                        },
                        new
                        {
                            ID = 172,
                            Name = "MITHRIL_ORE"
                        },
                        new
                        {
                            ID = 173,
                            Name = "ENCHANTED_HAY_BLOCK"
                        },
                        new
                        {
                            ID = 174,
                            Name = "ENCHANTED_PAPER"
                        },
                        new
                        {
                            ID = 175,
                            Name = "ENCHANTED_BONE"
                        },
                        new
                        {
                            ID = 176,
                            Name = "ENCHANTED_DIAMOND_BLOCK"
                        },
                        new
                        {
                            ID = 177,
                            Name = "SPOOKY_BAIT"
                        },
                        new
                        {
                            ID = 178,
                            Name = "SUPERIOR_FRAGMENT"
                        },
                        new
                        {
                            ID = 179,
                            Name = "EMERALD"
                        },
                        new
                        {
                            ID = 180,
                            Name = "ENCHANTED_RABBIT_FOOT"
                        },
                        new
                        {
                            ID = 181,
                            Name = "LIGHT_BAIT"
                        },
                        new
                        {
                            ID = 182,
                            Name = "ENCHANTED_ICE"
                        },
                        new
                        {
                            ID = 183,
                            Name = "HOT_POTATO_BOOK"
                        },
                        new
                        {
                            ID = 184,
                            Name = "CLAY_BALL"
                        },
                        new
                        {
                            ID = 185,
                            Name = "OLD_FRAGMENT"
                        },
                        new
                        {
                            ID = 186,
                            Name = "GREEN_GIFT"
                        },
                        new
                        {
                            ID = 187,
                            Name = "PACKED_ICE"
                        },
                        new
                        {
                            ID = 188,
                            Name = "WATER_LILY"
                        },
                        new
                        {
                            ID = 189,
                            Name = "HAMSTER_WHEEL"
                        },
                        new
                        {
                            ID = 190,
                            Name = "LOG_2"
                        },
                        new
                        {
                            ID = 191,
                            Name = "ENCHANTED_OBSIDIAN"
                        },
                        new
                        {
                            ID = 192,
                            Name = "ENCHANTED_COAL"
                        },
                        new
                        {
                            ID = 193,
                            Name = "COAL"
                        },
                        new
                        {
                            ID = 194,
                            Name = "ENCHANTED_QUARTZ"
                        },
                        new
                        {
                            ID = 195,
                            Name = "ENCHANTED_COAL_BLOCK"
                        },
                        new
                        {
                            ID = 196,
                            Name = "ENDER_PEARL"
                        },
                        new
                        {
                            ID = 197,
                            Name = "WEREWOLF_SKIN"
                        },
                        new
                        {
                            ID = 198,
                            Name = "ENCHANTED_PRISMARINE_CRYSTALS"
                        },
                        new
                        {
                            ID = 199,
                            Name = "DAEDALUS_STICK"
                        },
                        new
                        {
                            ID = 200,
                            Name = "ENCHANTED_WET_SPONGE"
                        },
                        new
                        {
                            ID = 201,
                            Name = "ENCHANTED_RAW_FISH"
                        },
                        new
                        {
                            ID = 202,
                            Name = "ENDER_STONE"
                        },
                        new
                        {
                            ID = 203,
                            Name = "FOUL_FLESH"
                        },
                        new
                        {
                            ID = 204,
                            Name = "QUARTZ"
                        },
                        new
                        {
                            ID = 205,
                            Name = "RAW_BEEF"
                        },
                        new
                        {
                            ID = 206,
                            Name = "JERRY_BOX_PURPLE"
                        },
                        new
                        {
                            ID = 207,
                            Name = "ENCHANTED_EYE_OF_ENDER"
                        },
                        new
                        {
                            ID = 208,
                            Name = "ECTOPLASM"
                        },
                        new
                        {
                            ID = 209,
                            Name = "SUGAR_CANE"
                        },
                        new
                        {
                            ID = 210,
                            Name = "MAGMA_CREAM"
                        },
                        new
                        {
                            ID = 211,
                            Name = "SHARK_BAIT"
                        },
                        new
                        {
                            ID = 212,
                            Name = "RED_GIFT"
                        },
                        new
                        {
                            ID = 213,
                            Name = "ENCHANTED_RAW_BEEF"
                        },
                        new
                        {
                            ID = 214,
                            Name = "JERRY_BOX_BLUE"
                        },
                        new
                        {
                            ID = 215,
                            Name = "ENCHANTED_FEATHER"
                        },
                        new
                        {
                            ID = 216,
                            Name = "ENCHANTED_SLIME_BLOCK"
                        },
                        new
                        {
                            ID = 217,
                            Name = "ENCHANTED_OAK_LOG"
                        },
                        new
                        {
                            ID = 218,
                            Name = "RABBIT_HIDE"
                        },
                        new
                        {
                            ID = 219,
                            Name = "WHITE_GIFT"
                        },
                        new
                        {
                            ID = 220,
                            Name = "RABBIT"
                        },
                        new
                        {
                            ID = 221,
                            Name = "SULPHUR"
                        },
                        new
                        {
                            ID = 222,
                            Name = "NETHER_STALK"
                        },
                        new
                        {
                            ID = 223,
                            Name = "DARK_BAIT"
                        },
                        new
                        {
                            ID = 224,
                            Name = "ENCHANTED_CARROT"
                        },
                        new
                        {
                            ID = 225,
                            Name = "ENCHANTED_PUMPKIN"
                        },
                        new
                        {
                            ID = 226,
                            Name = "GRIFFIN_FEATHER"
                        },
                        new
                        {
                            ID = 227,
                            Name = "ROTTEN_FLESH"
                        },
                        new
                        {
                            ID = 228,
                            Name = "ENCHANTED_COOKED_FISH"
                        },
                        new
                        {
                            ID = 229,
                            Name = "OBSIDIAN"
                        },
                        new
                        {
                            ID = 230,
                            Name = "MINNOW_BAIT"
                        },
                        new
                        {
                            ID = 231,
                            Name = "ENCHANTED_MAGMA_CREAM"
                        },
                        new
                        {
                            ID = 232,
                            Name = "ENCHANTED_FIREWORK_ROCKET"
                        },
                        new
                        {
                            ID = 233,
                            Name = "STARFALL"
                        },
                        new
                        {
                            ID = 234,
                            Name = "LEATHER"
                        },
                        new
                        {
                            ID = 235,
                            Name = "ENCHANTED_COOKED_MUTTON"
                        },
                        new
                        {
                            ID = 236,
                            Name = "REFINED_TITANIUM"
                        },
                        new
                        {
                            ID = 237,
                            Name = "ENCHANTED_RABBIT"
                        },
                        new
                        {
                            ID = 238,
                            Name = "MUTANT_NETHER_STALK"
                        },
                        new
                        {
                            ID = 239,
                            Name = "ENCHANTED_BREAD"
                        },
                        new
                        {
                            ID = 240,
                            Name = "FUMING_POTATO_BOOK"
                        },
                        new
                        {
                            ID = 241,
                            Name = "ENCHANTED_CHARCOAL"
                        },
                        new
                        {
                            ID = 242,
                            Name = "ENCHANTED_BLAZE_POWDER"
                        },
                        new
                        {
                            ID = 243,
                            Name = "SUMMONING_EYE"
                        },
                        new
                        {
                            ID = 244,
                            Name = "FISH_BAIT"
                        },
                        new
                        {
                            ID = 245,
                            Name = "SNOW_BLOCK"
                        },
                        new
                        {
                            ID = 246,
                            Name = "ENCHANTED_BAKED_POTATO"
                        },
                        new
                        {
                            ID = 247,
                            Name = "COMPACTOR"
                        },
                        new
                        {
                            ID = 248,
                            Name = "ENCHANTED_DIAMOND"
                        },
                        new
                        {
                            ID = 249,
                            Name = "BAZAAR_COOKIE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
