using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace SkyblockAuctionTracker.Models
{
    public partial class AMCDbContext : DbContext
    {
        public DbSet<BazaarProductIDMapping> BazaarProductIDMappings { get; set; }
        public DbSet<BazaarProductEntry> BazaarProductEntries { get; set; }
        public AMCDbContext()
        {
        }

        public AMCDbContext(DbContextOptions<AMCDbContext> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BazaarProductIDMapping>()
                .HasKey(mapping => new { mapping.ID, mapping.Name });

            modelBuilder.Entity<BazaarProductEntry>()
                .HasKey(entry => new { entry.Timestamp, entry.MappingID });

            SeedBazaarProductMappings(modelBuilder);

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        private void SeedBazaarProductMappings(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BazaarProductIDMapping>().HasData(
                new BazaarProductIDMapping { ID = 0, Name = "INK_SACK:3" },
                new BazaarProductIDMapping { ID = 1, Name = "BROWN_MUSHROOM" },
                new BazaarProductIDMapping { ID = 2, Name = "INK_SACK:4" },
                new BazaarProductIDMapping { ID = 3, Name = "SPOOKY_SHARD" },
                new BazaarProductIDMapping { ID = 4, Name = "TARANTULA_WEB" },
                new BazaarProductIDMapping { ID = 5, Name = "CARROT_ITEM" },
                new BazaarProductIDMapping { ID = 6, Name = "ENCHANTED_POTATO" },
                new BazaarProductIDMapping { ID = 7, Name = "EXP_BOTTLE" },
                new BazaarProductIDMapping { ID = 8, Name = "ENCHANTED_SLIME_BALL" },
                new BazaarProductIDMapping { ID = 9, Name = "JERRY_BOX_GREEN" },
                new BazaarProductIDMapping { ID = 10, Name = "ENCHANTED_RED_MUSHROOM" },
                new BazaarProductIDMapping { ID = 11, Name = "ENCHANTED_GOLDEN_CARROT" },
                new BazaarProductIDMapping { ID = 12, Name = "ENCHANTED_RABBIT_HIDE" },
                new BazaarProductIDMapping { ID = 13, Name = "ENCHANTED_BIRCH_LOG" },
                new BazaarProductIDMapping { ID = 14, Name = "ENCHANTED_GUNPOWDER" },
                new BazaarProductIDMapping { ID = 15, Name = "ENCHANTED_MELON" },
                new BazaarProductIDMapping { ID = 16, Name = "ENCHANTED_SUGAR" },
                new BazaarProductIDMapping { ID = 17, Name = "CACTUS" },
                new BazaarProductIDMapping { ID = 18, Name = "ENCHANTED_BLAZE_ROD" },
                new BazaarProductIDMapping { ID = 19, Name = "ENCHANTED_CAKE" },
                new BazaarProductIDMapping { ID = 20, Name = "PUMPKIN" },
                new BazaarProductIDMapping { ID = 21, Name = "ENCHANTED_BROWN_MUSHROOM" },
                new BazaarProductIDMapping { ID = 22, Name = "WHEAT" },
                new BazaarProductIDMapping { ID = 23, Name = "NURSE_SHARK_TOOTH" },
                new BazaarProductIDMapping { ID = 24, Name = "ENCHANTED_RAW_SALMON" },
                new BazaarProductIDMapping { ID = 25, Name = "ENCHANTED_GLISTERING_MELON" },
                new BazaarProductIDMapping { ID = 26, Name = "PRISMARINE_SHARD" },
                new BazaarProductIDMapping { ID = 27, Name = "ENCHANTED_EMERALD" },
                new BazaarProductIDMapping { ID = 28, Name = "PROTECTOR_FRAGMENT" },
                new BazaarProductIDMapping { ID = 29, Name = "ENCHANTED_SPIDER_EYE" },
                new BazaarProductIDMapping { ID = 30, Name = "RED_MUSHROOM" },
                new BazaarProductIDMapping { ID = 31, Name = "GRAND_EXP_BOTTLE" },
                new BazaarProductIDMapping { ID = 32, Name = "ENCHANTED_MELON_BLOCK" },
                new BazaarProductIDMapping { ID = 33, Name = "MUTTON" },
                new BazaarProductIDMapping { ID = 34, Name = "DIAMOND" },
                new BazaarProductIDMapping { ID = 35, Name = "WISE_FRAGMENT" },
                new BazaarProductIDMapping { ID = 36, Name = "SHARK_FIN" },
                new BazaarProductIDMapping { ID = 37, Name = "COBBLESTONE" },
                new BazaarProductIDMapping { ID = 38, Name = "REFINED_MITHRIL" },
                new BazaarProductIDMapping { ID = 39, Name = "RAW_FISH" },
                new BazaarProductIDMapping { ID = 40, Name = "SPIDER_EYE" },
                new BazaarProductIDMapping { ID = 41, Name = "ENCHANTED_PUFFERFISH" },
                new BazaarProductIDMapping { ID = 42, Name = "POTATO_ITEM" },
                new BazaarProductIDMapping { ID = 43, Name = "ENCHANTED_HUGE_MUSHROOM_1" },
                new BazaarProductIDMapping { ID = 44, Name = "REFINED_DIAMOND" },
                new BazaarProductIDMapping { ID = 45, Name = "ENCHANTED_COBBLESTONE" },
                new BazaarProductIDMapping { ID = 46, Name = "TIGHTLY_TIED_HAY_BALE" },
                new BazaarProductIDMapping { ID = 47, Name = "ENCHANTED_HUGE_MUSHROOM_2" },
                new BazaarProductIDMapping { ID = 48, Name = "PORK" },
                new BazaarProductIDMapping { ID = 49, Name = "PRISMARINE_CRYSTALS" },
                new BazaarProductIDMapping { ID = 50, Name = "ICE" },
                new BazaarProductIDMapping { ID = 51, Name = "TIGER_SHARK_TOOTH" },
                new BazaarProductIDMapping { ID = 52, Name = "HUGE_MUSHROOM_1" },
                new BazaarProductIDMapping { ID = 53, Name = "ICE_BAIT" },
                new BazaarProductIDMapping { ID = 54, Name = "HUGE_MUSHROOM_2" },
                new BazaarProductIDMapping { ID = 55, Name = "LOG_2:1" },
                new BazaarProductIDMapping { ID = 56, Name = "ENCHANTED_SNOW_BLOCK" },
                new BazaarProductIDMapping { ID = 57, Name = "STRING" },
                new BazaarProductIDMapping { ID = 58, Name = "GOLDEN_TOOTH" },
                new BazaarProductIDMapping { ID = 59, Name = "HYPER_CATALYST" },
                new BazaarProductIDMapping { ID = 60, Name = "RABBIT_FOOT" },
                new BazaarProductIDMapping { ID = 61, Name = "REDSTONE" },
                new BazaarProductIDMapping { ID = 62, Name = "JERRY_BOX_GOLDEN" },
                new BazaarProductIDMapping { ID = 63, Name = "PUMPKIN_GUTS" },
                new BazaarProductIDMapping { ID = 64, Name = "ENCHANTED_CACTUS_GREEN" },
                new BazaarProductIDMapping { ID = 65, Name = "BOOSTER_COOKIE" },
                new BazaarProductIDMapping { ID = 66, Name = "ENCHANTED_CARROT_ON_A_STICK" },
                new BazaarProductIDMapping { ID = 67, Name = "ENCHANTED_COOKIE" },
                new BazaarProductIDMapping { ID = 68, Name = "ENCHANTED_LAPIS_LAZULI_BLOCK" },
                new BazaarProductIDMapping { ID = 69, Name = "ENCHANTED_ENDSTONE" },
                new BazaarProductIDMapping { ID = 70, Name = "COLOSSAL_EXP_BOTTLE" },
                new BazaarProductIDMapping { ID = 71, Name = "ENCHANTED_SAND" },
                new BazaarProductIDMapping { ID = 72, Name = "ENCHANTED_STRING" },
                new BazaarProductIDMapping { ID = 73, Name = "STRONG_FRAGMENT" },
                new BazaarProductIDMapping { ID = 74, Name = "SLIME_BALL" },
                new BazaarProductIDMapping { ID = 75, Name = "ENCHANTED_ACACIA_LOG" },
                new BazaarProductIDMapping { ID = 76, Name = "HOLY_FRAGMENT" },
                new BazaarProductIDMapping { ID = 77, Name = "SNOW_BALL" },
                new BazaarProductIDMapping { ID = 78, Name = "ENCHANTED_EGG" },
                new BazaarProductIDMapping { ID = 79, Name = "SAND" },
                new BazaarProductIDMapping { ID = 80, Name = "SOUL_FRAGMENT" },
                new BazaarProductIDMapping { ID = 81, Name = "RAW_CHICKEN" },
                new BazaarProductIDMapping { ID = 82, Name = "ANCIENT_CLAW" },
                new BazaarProductIDMapping { ID = 83, Name = "ENCHANTED_GHAST_TEAR" },
                new BazaarProductIDMapping { ID = 84, Name = "ENCHANTED_LAPIS_LAZULI" },
                new BazaarProductIDMapping { ID = 85, Name = "ENCHANTED_COCOA" },
                new BazaarProductIDMapping { ID = 86, Name = "CARROT_BAIT" },
                new BazaarProductIDMapping { ID = 87, Name = "SEEDS" },
                new BazaarProductIDMapping { ID = 88, Name = "ENCHANTED_LEATHER" },
                new BazaarProductIDMapping { ID = 89, Name = "ENCHANTED_SPONGE" },
                new BazaarProductIDMapping { ID = 90, Name = "ENCHANTED_SHARK_FIN" },
                new BazaarProductIDMapping { ID = 91, Name = "HAY_BLOCK" },
                new BazaarProductIDMapping { ID = 92, Name = "FLINT" },
                new BazaarProductIDMapping { ID = 93, Name = "INK_SACK" },
                new BazaarProductIDMapping { ID = 94, Name = "ENCHANTED_ROTTEN_FLESH" },
                new BazaarProductIDMapping { ID = 95, Name = "ENCHANTED_SPRUCE_LOG" },
                new BazaarProductIDMapping { ID = 96, Name = "WOLF_TOOTH" },
                new BazaarProductIDMapping { ID = 97, Name = "ENCHANTED_GRILLED_PORK" },
                new BazaarProductIDMapping { ID = 98, Name = "ENCHANTED_NETHER_STALK" },
                new BazaarProductIDMapping { ID = 99, Name = "ENCHANTED_REDSTONE_BLOCK" },
                new BazaarProductIDMapping { ID = 100, Name = "ENCHANTED_QUARTZ_BLOCK" },
                new BazaarProductIDMapping { ID = 101, Name = "ENCHANTED_ANCIENT_CLAW" },
                new BazaarProductIDMapping { ID = 102, Name = "GREEN_CANDY" },
                new BazaarProductIDMapping { ID = 103, Name = "ENCHANTED_REDSTONE" },
                new BazaarProductIDMapping { ID = 104, Name = "ENCHANTED_REDSTONE_LAMP" },
                new BazaarProductIDMapping { ID = 105, Name = "GREAT_WHITE_SHARK_TOOTH" },
                new BazaarProductIDMapping { ID = 106, Name = "GRAVEL" },
                new BazaarProductIDMapping { ID = 107, Name = "MELON" },
                new BazaarProductIDMapping { ID = 108, Name = "ENCHANTED_PACKED_ICE" },
                new BazaarProductIDMapping { ID = 109, Name = "ENCHANTED_LAVA_BUCKET" },
                new BazaarProductIDMapping { ID = 110, Name = "RAW_FISH:3" },
                new BazaarProductIDMapping { ID = 111, Name = "ENCHANTED_PRISMARINE_SHARD" },
                new BazaarProductIDMapping { ID = 112, Name = "ENCHANTED_IRON_BLOCK" },
                new BazaarProductIDMapping { ID = 113, Name = "RECOMBOBULATOR_3000" },
                new BazaarProductIDMapping { ID = 114, Name = "ENCHANTED_CARROT_STICK" },
                new BazaarProductIDMapping { ID = 115, Name = "BONE" },
                new BazaarProductIDMapping { ID = 116, Name = "RAW_FISH:2" },
                new BazaarProductIDMapping { ID = 117, Name = "RAW_FISH:1" },
                new BazaarProductIDMapping { ID = 118, Name = "REVENANT_FLESH" },
                new BazaarProductIDMapping { ID = 119, Name = "ENCHANTED_PORK" },
                new BazaarProductIDMapping { ID = 120, Name = "ENCHANTED_GLOWSTONE" },
                new BazaarProductIDMapping { ID = 121, Name = "FEATHER" },
                new BazaarProductIDMapping { ID = 122, Name = "NETHERRACK" },
                new BazaarProductIDMapping { ID = 123, Name = "WHALE_BAIT" },
                new BazaarProductIDMapping { ID = 124, Name = "SPONGE" },
                new BazaarProductIDMapping { ID = 125, Name = "BLAZE_ROD" },
                new BazaarProductIDMapping { ID = 126, Name = "ENCHANTED_DARK_OAK_LOG" },
                new BazaarProductIDMapping { ID = 127, Name = "YOUNG_FRAGMENT" },
                new BazaarProductIDMapping { ID = 128, Name = "ENCHANTED_CLOWNFISH" },
                new BazaarProductIDMapping { ID = 129, Name = "REFINED_MINERAL" },
                new BazaarProductIDMapping { ID = 130, Name = "ENCHANTED_GOLD" },
                new BazaarProductIDMapping { ID = 131, Name = "ENCHANTED_RAW_CHICKEN" },
                new BazaarProductIDMapping { ID = 132, Name = "ENCHANTED_WATER_LILY" },
                new BazaarProductIDMapping { ID = 133, Name = "LOG:1" },
                new BazaarProductIDMapping { ID = 134, Name = "TITANIUM_ORE" },
                new BazaarProductIDMapping { ID = 135, Name = "BLUE_SHARK_TOOTH" },
                new BazaarProductIDMapping { ID = 136, Name = "CATALYST" },
                new BazaarProductIDMapping { ID = 137, Name = "LOG:3" },
                new BazaarProductIDMapping { ID = 138, Name = "LOG:2" },
                new BazaarProductIDMapping { ID = 139, Name = "BLESSED_BAIT" },
                new BazaarProductIDMapping { ID = 140, Name = "ENCHANTED_GLOWSTONE_DUST" },
                new BazaarProductIDMapping { ID = 141, Name = "ENCHANTED_INK_SACK" },
                new BazaarProductIDMapping { ID = 142, Name = "ENCHANTED_CACTUS" },
                new BazaarProductIDMapping { ID = 143, Name = "ENCHANTED_SUGAR_CANE" },
                new BazaarProductIDMapping { ID = 144, Name = "ENCHANTED_COOKED_SALMON" },
                new BazaarProductIDMapping { ID = 145, Name = "ENCHANTED_SEEDS" },
                new BazaarProductIDMapping { ID = 146, Name = "LOG" },
                new BazaarProductIDMapping { ID = 147, Name = "JACOBS_TICKET" },
                new BazaarProductIDMapping { ID = 148, Name = "ENCHANTED_BONE_BLOCK" },
                new BazaarProductIDMapping { ID = 149, Name = "GHAST_TEAR" },
                new BazaarProductIDMapping { ID = 150, Name = "ENCHANTED_ENDER_PEARL" },
                new BazaarProductIDMapping { ID = 151, Name = "UNSTABLE_FRAGMENT" },
                new BazaarProductIDMapping { ID = 152, Name = "PURPLE_CANDY" },
                new BazaarProductIDMapping { ID = 153, Name = "ENCHANTED_FERMENTED_SPIDER_EYE" },
                new BazaarProductIDMapping { ID = 154, Name = "SPIKED_BAIT" },
                new BazaarProductIDMapping { ID = 155, Name = "POLISHED_PUMPKIN" },
                new BazaarProductIDMapping { ID = 156, Name = "ENCHANTED_GOLD_BLOCK" },
                new BazaarProductIDMapping { ID = 157, Name = "ENCHANTED_JUNGLE_LOG" },
                new BazaarProductIDMapping { ID = 158, Name = "ENCHANTED_FLINT" },
                new BazaarProductIDMapping { ID = 159, Name = "IRON_INGOT" },
                new BazaarProductIDMapping { ID = 160, Name = "ENCHANTED_EMERALD_BLOCK" },
                new BazaarProductIDMapping { ID = 161, Name = "ENCHANTED_CLAY_BALL" },
                new BazaarProductIDMapping { ID = 162, Name = "GLOWSTONE_DUST" },
                new BazaarProductIDMapping { ID = 163, Name = "GOLD_INGOT" },
                new BazaarProductIDMapping { ID = 164, Name = "REVENANT_VISCERA" },
                new BazaarProductIDMapping { ID = 165, Name = "TARANTULA_SILK" },
                new BazaarProductIDMapping { ID = 166, Name = "TITANIC_EXP_BOTTLE" },
                new BazaarProductIDMapping { ID = 167, Name = "ENCHANTED_MUTTON" },
                new BazaarProductIDMapping { ID = 168, Name = "ENCHANTED_IRON" },
                new BazaarProductIDMapping { ID = 169, Name = "SUPER_COMPACTOR_3000" },
                new BazaarProductIDMapping { ID = 170, Name = "SUPER_EGG" },
                new BazaarProductIDMapping { ID = 171, Name = "STOCK_OF_STONKS" },
                new BazaarProductIDMapping { ID = 172, Name = "MITHRIL_ORE" },
                new BazaarProductIDMapping { ID = 173, Name = "ENCHANTED_HAY_BLOCK" },
                new BazaarProductIDMapping { ID = 174, Name = "ENCHANTED_PAPER" },
                new BazaarProductIDMapping { ID = 175, Name = "ENCHANTED_BONE" },
                new BazaarProductIDMapping { ID = 176, Name = "ENCHANTED_DIAMOND_BLOCK" },
                new BazaarProductIDMapping { ID = 177, Name = "SPOOKY_BAIT" },
                new BazaarProductIDMapping { ID = 178, Name = "SUPERIOR_FRAGMENT" },
                new BazaarProductIDMapping { ID = 179, Name = "EMERALD" },
                new BazaarProductIDMapping { ID = 180, Name = "ENCHANTED_RABBIT_FOOT" },
                new BazaarProductIDMapping { ID = 181, Name = "LIGHT_BAIT" },
                new BazaarProductIDMapping { ID = 182, Name = "ENCHANTED_ICE" },
                new BazaarProductIDMapping { ID = 183, Name = "HOT_POTATO_BOOK" },
                new BazaarProductIDMapping { ID = 184, Name = "CLAY_BALL" },
                new BazaarProductIDMapping { ID = 185, Name = "OLD_FRAGMENT" },
                new BazaarProductIDMapping { ID = 186, Name = "GREEN_GIFT" },
                new BazaarProductIDMapping { ID = 187, Name = "PACKED_ICE" },
                new BazaarProductIDMapping { ID = 188, Name = "WATER_LILY" },
                new BazaarProductIDMapping { ID = 189, Name = "HAMSTER_WHEEL" },
                new BazaarProductIDMapping { ID = 190, Name = "LOG_2" },
                new BazaarProductIDMapping { ID = 191, Name = "ENCHANTED_OBSIDIAN" },
                new BazaarProductIDMapping { ID = 192, Name = "ENCHANTED_COAL" },
                new BazaarProductIDMapping { ID = 193, Name = "COAL" },
                new BazaarProductIDMapping { ID = 194, Name = "ENCHANTED_QUARTZ" },
                new BazaarProductIDMapping { ID = 195, Name = "ENCHANTED_COAL_BLOCK" },
                new BazaarProductIDMapping { ID = 196, Name = "ENDER_PEARL" },
                new BazaarProductIDMapping { ID = 197, Name = "WEREWOLF_SKIN" },
                new BazaarProductIDMapping { ID = 198, Name = "ENCHANTED_PRISMARINE_CRYSTALS" },
                new BazaarProductIDMapping { ID = 199, Name = "DAEDALUS_STICK" },
                new BazaarProductIDMapping { ID = 200, Name = "ENCHANTED_WET_SPONGE" },
                new BazaarProductIDMapping { ID = 201, Name = "ENCHANTED_RAW_FISH" },
                new BazaarProductIDMapping { ID = 202, Name = "ENDER_STONE" },
                new BazaarProductIDMapping { ID = 203, Name = "FOUL_FLESH" },
                new BazaarProductIDMapping { ID = 204, Name = "QUARTZ" },
                new BazaarProductIDMapping { ID = 205, Name = "RAW_BEEF" },
                new BazaarProductIDMapping { ID = 206, Name = "JERRY_BOX_PURPLE" },
                new BazaarProductIDMapping { ID = 207, Name = "ENCHANTED_EYE_OF_ENDER" },
                new BazaarProductIDMapping { ID = 208, Name = "ECTOPLASM" },
                new BazaarProductIDMapping { ID = 209, Name = "SUGAR_CANE" },
                new BazaarProductIDMapping { ID = 210, Name = "MAGMA_CREAM" },
                new BazaarProductIDMapping { ID = 211, Name = "SHARK_BAIT" },
                new BazaarProductIDMapping { ID = 212, Name = "RED_GIFT" },
                new BazaarProductIDMapping { ID = 213, Name = "ENCHANTED_RAW_BEEF" },
                new BazaarProductIDMapping { ID = 214, Name = "JERRY_BOX_BLUE" },
                new BazaarProductIDMapping { ID = 215, Name = "ENCHANTED_FEATHER" },
                new BazaarProductIDMapping { ID = 216, Name = "ENCHANTED_SLIME_BLOCK" },
                new BazaarProductIDMapping { ID = 217, Name = "ENCHANTED_OAK_LOG" },
                new BazaarProductIDMapping { ID = 218, Name = "RABBIT_HIDE" },
                new BazaarProductIDMapping { ID = 219, Name = "WHITE_GIFT" },
                new BazaarProductIDMapping { ID = 220, Name = "RABBIT" },
                new BazaarProductIDMapping { ID = 221, Name = "SULPHUR" },
                new BazaarProductIDMapping { ID = 222, Name = "NETHER_STALK" },
                new BazaarProductIDMapping { ID = 223, Name = "DARK_BAIT" },
                new BazaarProductIDMapping { ID = 224, Name = "ENCHANTED_CARROT" },
                new BazaarProductIDMapping { ID = 225, Name = "ENCHANTED_PUMPKIN" },
                new BazaarProductIDMapping { ID = 226, Name = "GRIFFIN_FEATHER" },
                new BazaarProductIDMapping { ID = 227, Name = "ROTTEN_FLESH" },
                new BazaarProductIDMapping { ID = 228, Name = "ENCHANTED_COOKED_FISH" },
                new BazaarProductIDMapping { ID = 229, Name = "OBSIDIAN" },
                new BazaarProductIDMapping { ID = 230, Name = "MINNOW_BAIT" },
                new BazaarProductIDMapping { ID = 231, Name = "ENCHANTED_MAGMA_CREAM" },
                new BazaarProductIDMapping { ID = 232, Name = "ENCHANTED_FIREWORK_ROCKET" },
                new BazaarProductIDMapping { ID = 233, Name = "STARFALL" },
                new BazaarProductIDMapping { ID = 234, Name = "LEATHER" },
                new BazaarProductIDMapping { ID = 235, Name = "ENCHANTED_COOKED_MUTTON" },
                new BazaarProductIDMapping { ID = 236, Name = "REFINED_TITANIUM" },
                new BazaarProductIDMapping { ID = 237, Name = "ENCHANTED_RABBIT" },
                new BazaarProductIDMapping { ID = 238, Name = "MUTANT_NETHER_STALK" },
                new BazaarProductIDMapping { ID = 239, Name = "ENCHANTED_BREAD" },
                new BazaarProductIDMapping { ID = 240, Name = "FUMING_POTATO_BOOK" },
                new BazaarProductIDMapping { ID = 241, Name = "ENCHANTED_CHARCOAL" },
                new BazaarProductIDMapping { ID = 242, Name = "ENCHANTED_BLAZE_POWDER" },
                new BazaarProductIDMapping { ID = 243, Name = "SUMMONING_EYE" },
                new BazaarProductIDMapping { ID = 244, Name = "FISH_BAIT" },
                new BazaarProductIDMapping { ID = 245, Name = "SNOW_BLOCK" },
                new BazaarProductIDMapping { ID = 246, Name = "ENCHANTED_BAKED_POTATO" },
                new BazaarProductIDMapping { ID = 247, Name = "COMPACTOR" },
                new BazaarProductIDMapping { ID = 248, Name = "ENCHANTED_DIAMOND" },
                new BazaarProductIDMapping { ID = 249, Name = "BAZAAR_COOKIE" }
            );
        }
    }
}
